### ISSUE TITLE
How to start from different port than 843?

### ISSUE THREAD

**Issue by F1LT3R** [gimite/web-socket-js#160]
Is it easy to change the port it listens to? I don't want to run sudo to start this server up if possible.

**Comment by gimite** [comment]
If the question is "How to let web-socket-js to talk to a specific WebSocket port", then you can do it by e.g.,:

    var ws = new WebSocket("ws://example.com:12345");

If the question is "How to run WebSocket server at a specific port", then it depends on what WebSocket server you are using. (em-websocket? pywebsocket?)

**Comment by F1LT3R** [comment]
Cool! I will give this a try later.
