### ISSUE TITLE
policy server file domain  match error 

### ISSUE THREAD

**Issue by HunterPan** [gimite/web-socket-js#163]
for example：
   first rule  `<allow-access-from domain="*.test.com" to-ports="*" />`
    second rule `<allow-access-from domain="10.44.1.10" to-ports="*" />`
the first rule can not sucess,flex error:(SecurityError: Error #2048)
but the second rule sucess.
why? I google many times but not solved .

**Comment by gimite** [comment]
Hm I'm not sure. What if it's an exact host name without "*"? e.g., "foo.test.com"

**Comment by HunterPan** [comment]
@gimite , I got answer.
the exactly rule must by written in correct format. 
bad:  <allow-access-from domain="*.test.com" to-ports="*" />
good:<allow-access-from domain="*.test.com" to-ports="*"/>
note  no space at end of line  in good rule.
because I had no more knowlage about these,so  do you sure  only  ' web-socket-js' has the problem?
thanks a lot.
