### ISSUE TITLE
Cant make it work even with perl socket policy server

### ISSUE THREAD

**Issue by vedmack** [gimite/web-socket-js#164]
Hi,

Im trying to make websokets to work on ie9, at start I was getting 
`
[WebSocket] cannot connect to Web Socket server at ws://localhost/mywebaspp/some/path (SecurityError: Error #2048)
make sure the server is running and Flash socket policy file is correctly placed`

Then after running the socketpolicy.pl I started to get another error message 
`[WebSocket] bad response: HTTP/1.1 302 Found`

The websokets works just fine on chrome (in which I'm not using the _swfobject.js/web-socket-js/_ which are placed inside a `<!--[if IE 9]><![endif]-->` tag)

Any ideas on what else I should do to make it work? (on my windows / tomcat 7)

Thanks ahead

**Comment by gimite** [comment]
web-socket-js doesn't support HTTP 302 response (redirect). You can workaround the problem by not using 302 redirect in your websocket server.

I didn't know that 302 redirect is allowed in WebSocket :)
