### ISSUE TITLE
Confirm the license version

### ISSUE THREAD

**Issue by PeterDaveHello** [gimite/web-socket-js#168]
Hi there,

May I know the version of MIT you are using? I think it's as important as a license, many thanks!

ref: https://spdx.org/licenses/

**Comment by gimite** [comment]
Sorry for late.

It's New BSD License, not MIT License. See
https://github.com/gimite/web-socket-js/blob/master/LICENSE.txt
for the exact license term.

**Comment by PeterDaveHello** [comment]
Hi @gimite, may I ask the exactly version of the new BSD license you are using? There are several versions, thanks.

**Comment by gimite** [comment]
I believe it is something called 'BSD 3-clause "New" or "Revised" License':
https://spdx.org/licenses/BSD-3-Clause.html#licenseText
See the license text to verify:
https://github.com/gimite/web-socket-js/blob/master/LICENSE.txt

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
I add the license info on cdnjs now:
https://github.com/cdnjs/cdnjs/commit/863f61eb9d7607f96bf3a46760f9e5b6f5323c71
