### ISSUE TITLE
don't work at ie 8

### ISSUE THREAD

**Issue by kyytyp** [gimite/web-socket-js#174]
chrome and ie11 is ok ,but not work on ie8。

error message:
用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
时间戳: Fri, 20 Jan 2017 06:44:46 UTC
消息: 例外被抛出且未被接住
行: 78
字符: 7
代码: 0
URI: http://192.168.1.52:8081/Chat/web_socket.js

on 78 line:throw "INVALID_STATE_ERR: Web Socket connection has not been established";

**Comment by gimite** [comment]
Can you follow:
https://github.com/gimite/web-socket-js#troubleshooting
and describe its result? Especially:

* Did you put Flash socket policy file on your server?
* Don't you use HTTP proxy on your browser?

**Comment by kyytyp** [comment]
if i don't run as ruby server, my server is java tomcat8 , it's ok?
it's must need  1.client  2.ruby server 3.java tomcat ,  three?

**Comment by gimite** [comment]
You need:
- Client side implementation (Your JS code + web-socket-js bundle)
- WebSocket server (in Java in your case)
- Flash socket policy file server (in any languages, there are implementations in Ruby, Perl, node-js)

See here for details and links to implementations of Flash socket policy server:
https://github.com/gimite/web-socket-js#flash-socket-policy-file
