### ISSUE TITLE
Real-time Collaborative editor

### ISSUE THREAD

**Issue by anantjain6** [gimite/web-socket-js#181]
Hello,
I want to build a real-time collaborative Textarea (HTML tag) which has functionality like google Docs where multiple people can write collaboratively.
I don't have much knowledge of sockets but this repository looks me of use for it
It will be great if someone can give some guidance to use this repository to develop a Real-Time Collaborative textarea

**Comment by gimite** [comment]
Sorry for late.

You can probably use WebSockets directly:
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

Now that most browsers support WebSockets natively, while many of them rather stopped supporting Flash, I would say the role of this library has almost ended, except when you want to support very old browsers.
