### ISSUE TITLE
wss doesn't work

### ISSUE THREAD

**Issue by daralthus** [gimite/web-socket-js#28]
Hey there! A secure connection support would be awesome, I did the homework and found http://github.com/kanaka/noVNC he has a modified version of web-socket-js but I can't get it to work,
There's no FAB init callback with https and wss. Hopefully you could do it. :)

**Comment by Shaun-Avaya** [comment]
Hi @daralthus I get the same issue with this web_socket.js: https + wss, and the policy allowed for port 443 there's no policy  error, but I can not open the scoket connection. how do you fix the issue?
